name: "Lcf Blogs"
description: "炼丹怪的个人博客"

avatar: https://LLLcf.github.io/images/head.jpg
favicon: https://LLLcf.github.io/images/favicon.ico

navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 分类
    url: /tags

paginate: 8

excerpt_separator: <!-- more -->

footer-links:
  zhihu: zhihu.com/people/lcfff_0705
  email: 15002795682@163.com
  facebook:
  github: LLLcf
  rss: # just type anything here for a working RSS icon
  twitter: 
  youtube:

footer-text: Copyright (c) 2025 Lcfff

url: https://LLLcf.github.io

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Gitalk 评论系统配置
gitalk:
  clientID: "Ov23licU6mbTJ3uvoJCT"
  clientSecret: "2e525b54587563534fcd1b1c30d3c3e70f79c33e"
  repo: "LLLcf.github.io"  # 评论存储的仓库（通常是博客仓库）
  owner: "LLLcf"           # 仓库所有者GitHub用户名
  admin: ["LLLcf"]         # 有权管理评论的用户